### ISSUE TITLE
Set up cloud storage

### ISSUE THREAD

**Issue by danielplont** [Fuckass-inc/The-Server#11]
Gotta decide on a platform first

**Comment by danielplont** [comment]
Gotta decide on a platform first

**Comment by kingashen** [comment]
owncloud is the best bet i can find super easy and all that jazz, tried installing but plugin failed, i understand a good amount about jails so if you want i can commit the purge just let me know what you wanna do

**Comment by danielplont** [comment]
Set owncloud directory to cloud data set instead of default

**Comment by danielplont** [comment]
Own cloud installed.
