### ISSUE TITLE
Update/Review Pihole filters

### ISSUE THREAD

**Issue by danielplont** [Fuckass-inc/The-Server#16]
Some banner ads and youtube pre-roll videos are still being displayed. Pihole might be set up to default to less extreme ad-blocking lists since it's a network-wide solution.

**Comment by danielplont** [comment]
Some banner ads and youtube pre-roll videos are still being displayed. Pihole might be set up to default to less extreme ad-blocking lists since it's a network-wide solution.

**Comment by danielplont** [comment]
Is it properly configured to support IPv6? I see IPv4 addresses getting blocked but IPv6 is getting through.

**Comment by kingashen** [comment]
pihole cannot block youtube that well, also it seems FreeNAS has broken pihole cause FreeNAS wasn't setup as static yet so now pihole isn't connecting to the internet

**Comment by kingashen** [comment]
pihole up and running reconfigured on the server side test if this works if not it could be a router side issue

**Comment by kingashen** [comment]
added 8 more lists all ads should be DOA
