### ISSUE TITLE
New Router Bug Thread

### ISSUE THREAD

**Issue by kingashen** [Fuckass-inc/The-Server#18]
Submit all issues caused by new router

**Comment by kingashen** [comment]
freenas load time in GUI is slower than normal to a noticeable amount.

**Comment by danielplont** [comment]
I have this crazy idea, nuking the freenas OS and starting fresh. Eat fresh.

**Comment by kingashen** [comment]
after finally getting back online and reinstalling ubuntu server I wanna say no, but fuck it Eat Fresh.

**Comment by danielplont** [comment]
Sever is nuked and currently no issues with the new router. We can open new issues for the router if we encounter any.
